SINGLE_VALUES = ["zero", "one", "two", "three", "four",
                 "five", "six", "seven", "eight", "nine"]
TENS = {
    "one zero": "Ten",
    "one one": "Eleven",
    "one two": "Twelve",
    "one three": "Thirteen",
    "one four": "Fourteen",
    "one five": "Fifteen",
    "one six": "Sixteen",
    "one seven": "Seventeen",
    "one eight": "Eighteen",
    "one nine": "Nineteen",
}
TWENTIES = {
    "two zero": "Twenty",
    "two one": "Twenty one",
    "two two": "Twenty two",
    "two three": "Twenty three",
    "two four": "Twenty four",
    "two five": "Twenty five",
    "two six": "Twenty six",
    "two seven": "Twenty seven",
    "two eight": "Twenty eight",
    "two nine": "Twenty nine",
}
THIRTIES = {
    "three zero": "Thirty",
    "three one": "Thirty one",
    "three two": "Thirty two",
    "three three": "Thirty three",
    "three four": "Thirty four",
    "three five": "Thirty five",
    "three six": "Thirty six",
    "three seven": "Thirty seven",
    "three eight": "Thirty eight",
    "three nine": "Thirty nine",
}
FORTIES = {
    "four zero": "Forty",
    "four one": "Forty one",
    "four two": "Forty two",
    "four three": "Forty three",
    "four four": "Forty four",
    "four five": "Forty five",
    "four six": "Forty six",
    "four seven": "Forty seven",
    "four eight": "Forty eight",
    "four nine": "Forty nine",
}
FIFTIES = {
    "five zero": "Fifty",
    "five one": "Fifty one",
    "five two": "Fifty two",
    "five three": "Fifty three",
    "five four": "Fifty four",
    "five five": "Fifty five",
    "five six": "Fifty six",
    "five seven": "Fifty seven",
    "five eight": "Fifty eight",
    "five nine": "Fifty nine",
}
SIXTIES = {
    "six zero": "Sixty",
    "six one": "Sixty one",
    "six two": "Sixty two",
    "six three": "Sixty three",
    "six four": "Sixty four",
    "six five": "Sixty five",
    "six six": "Sixty six",
    "six seven": "Sixty seven",
    "six eight": "Sixty eight",
    "six nine": "Sixty nine",
}
SEVENTIES = {
    "seven zero": "Seventy",
    "seven one": "Seventy one",
    "seven two": "Seventy two",
    "seven three": "Seventy three",
    "seven four": "Seventy four",
    "seven five": "Seventy five",
    "seven six": "Seventy six",
    "seven seven": "Seventy seven",
    "seven eight": "Seventy eight",
    "seven nine": "Seventy nine",
}
EIGHTIES = {
    "eight zero": "Eighty",
    "eight one": "Eighty one",
    "eight two": "Eighty two",
    "eight three": "Eighty three",
    "eight four": "Eighty four",
    "eight five": "Eighty five",
    "eight six": "Eighty six",
    "eight seven": "Eighty seven",
    "eight eight": "Eighty eight",
    "eight nine": "Eighty nine",
}
NINETIES = {
    "nine zero": "Ninety",
    "nine one": "Ninety one",
    "nine two": "Ninety two",
    "nine three": "Ninety three",
    "nine four": "Ninety four",
    "nine five": "Ninety five",
    "nine six": "Ninety six",
    "nine seven": "Ninety seven",
    "nine eight": "Ninety eight",
    "nine nine": "Ninety nine",
}
UNIT = [SINGLE_VALUES, TENS, TWENTIES, THIRTIES, FORTIES, FIFTIES, SIXTIES,
        SEVENTIES, EIGHTIES, NINETIES, ]
